version: '3.8'

services:
  backend:
    build:
      context: ./backend  
    ports:
      - "8000:8000" 
    depends_on:
      - mongodb 
    environment:
      MONGO_URL: mongodb://mongodb:27017  

  frontend:
    build:
      context: ./frontend  
    ports:
      - "3000:3000"  

  mongodb:
    image: mongo:5.0
    ports:
      - "27017:27017" 
    volumes:
      - mongo-data:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: password
      MONGO_INITDB_DATABASE: db_test

volumes:
  mongo-data:
