{
 "title": "Server Stats",
 "description": "This dashboard containts server metrics.\n",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Good Requests",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(http_all_requests_total{status=\"2xx\", handler!=\"/metrics\"}) by (handler)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "SEVER INTERNAL ERROR ",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "sum(http_all_requests_total{status=\"5xx\"}) by (handler)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Number of Bad Requests",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "sum(http_all_requests_total{status=\"4xx\"}) by (handler)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Peticiones que duren más de 2.5 segundos",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(http_all_request_duration_seconds_count) by (handler) - sum(http_all_request_duration_seconds_bucket{le=\"2.5\"}) by (handler)\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "TimeSeries",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "targets": [
    {
     "expr": "sum(http_all_request_duration_seconds_count) by (handler) - sum(http_all_request_duration_seconds_bucket{le=\"2.5\"}) by (handler)\n",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}