{
 "title": "Combat User Preferences",
 "time": { "from": "2024-09-24T08:56:20.916Z", "to": "2024-10-10T08:56:20.980Z" },
 "panels": [
  {
   "title": "Visitas Home",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "http_all_requests_total{handler=\"/\",status=\"2xx\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Combat Preferences",
   "type": "piechart",
   "description": "Esté gráfica busca comparar las acciones realizadas por los jugadores en cada combate.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (handler) (http_all_requests_total{handler=~\"/combat/(attack|defend|ability)\"})\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Nivel de Jugadores",
   "type": "barchart",
   "description": "Acá se muestra el nivel actual de cada jugador",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "sum(player_level) by (player_name)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Daño inflingido por jugadores",
   "type": "barchart",
   "description": "Esta grárfica un top 10 muestra el daño inflingido por los jugadores.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "expr": "topk(10, sum(player_damage_total) by (player_name))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Derrotas por jugador",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "targets": [
    {
     "expr": "sum by (player_name) (combat_outcomes_total{outcome=\"lose\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Victorias por jugador mensuales",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "targets": [
    {
     "expr": "sum by (player_name) (combat_outcomes_total{outcome=\"win\"})",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}