name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

# Necesitamos hacer que trabaje con nuestros contenedores.
jobs:
  test:
    runs-on: ubuntu-22.04
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Docker Compose
      run: |
        sudo apt-get update
        sudo apt-get install docker-compose
    
    - name: Build and run containers
      run: |
        docker compose -f compose.yml up -d --build

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.12'
    - name: Install dependencies
      run: |
        cd backend
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Run tests
      run: |
        cd backend
        export PYTHONPATH=$PYTHONPATH:$(pwd)
        pytest