name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

# Necesitamos hacer que trabaje con nuestros contenedores.
jobs:
  test:
    runs-on: ubuntu-22.04
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Docker Compose
      run: |
        sudo apt-get update
        sudo apt-get install docker-compose
    
    - name: Build and run containers
      run: |
        docker compose -f compose.yml up -d --build

  black-formatter:
    name: Black Code Formatter
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: rickstaa/action-black@v1
        with:
          black_args: ". --check"

